### ISSUE TITLE
Signs lose their text when built through blueprint by robots.

### ISSUE THREAD

**Issue by Adilf** [NiftyManiac/factorio-stickynotes#16]
When autoshow tick is set and a sign is blueprinted, upon placing the blueprint the text appears, but when robot builds the sign, a new text object is created without hiding set up and with default contents.
If you hold the selection on the text till the sign is built, then both old and new texts are overlapped.

**Comment by NiftyManiac** [comment]
Already fixed, will be in the next release.

**Comment by Adilf** [comment]
Nah, not fixed. Not in expected way at least.
Now if text is with 'autoshow' attribute, the message appears when blueprint is placed, but it is lost forewer in a second.
After that opening of the sign just creates new placeholder text.

**Comment by NiftyManiac** [comment]
Hmm. I've fixed some more sign related stuff that I'll push in 2.1.3 today and I'll play around to make sure it's actually fixed this time :)

**Comment by NiftyManiac** [comment]
Alright should actually be fixed in 2.1.3.
