### ISSUE TITLE
Text overflow

### ISSUE THREAD

**Issue by Nexela** [NiftyManiac/factorio-stickynotes#3]
Easy to reproduce, just copy/paste repeatedly a lot of text into the sticky text bar.

Secondary thoughts When we hit "max length"  Throw a warning but don't return.  cap the "saved" string to the max and ignore the rest if possible.

 288.018 Error MainLoop.cpp:788: Exception at tick 113250: Error while running event on_gui_text_changed (ID 2)
__StickyNotes__/control.lua:153: attempt to perform arithmetic on field '?' (a nil value)

Line 153: signal_vals[signal_i+2] = signal_vals[signal_i+2] + val * 2 ^ shift

![image](https://cloud.githubusercontent.com/assets/13972192/22423610/674caa12-e6c0-11e6-9bcf-45541270951a.png)

**Comment by NiftyManiac** [comment]
Yeah, I had this in my todo list but never put it up here. There's some logic with checking the limit in encodeNote() but in the wrong place (it errors before hitting the check). Will fix when I get a moment.

**Comment by NiftyManiac** [comment]
Fixed in https://github.com/NiftyManiac/factorio-stickynotes/commit/5927b8d0d0a4ad4c2cf4a1ce328c216d4f4a41d8
