### ISSUE TITLE
Many invis-notes placed when dragging a blueprint

### ISSUE THREAD

**Issue by NiftyManiac** [NiftyManiac/factorio-stickynotes#5]

**Comment by Nexela** [comment]
Have not had any time this weekend to look into this. It might be related to the not-colliding-with-self entity flag.

**Comment by NiftyManiac** [comment]
Fixed in https://github.com/NiftyManiac/factorio-stickynotes/commit/534b6556dd9c655b782dd2332afcbd2d0be1e519
