### ISSUE TITLE
Notes don't get deleted in some circumstances

### ISSUE THREAD

**Issue by NiftyManiac** [NiftyManiac/factorio-stickynotes#7]
A ghost with a note is placed. If a new building is placed on top of the ghost, the ghost dies but the note stays alive.

**Comment by NiftyManiac** [comment]
on_preplayer_mined_item is fired when a note is destroyed via right-click.
Nothing is fired if 

- it is replaced with the real thing by a robot or player
- **it disappears when an overlapping building is placed**
- **it disappears when the deconstruction planner is used**

**Comment by Nexela** [comment]
Could probably be solved by not reviving the invis-note until after the entity it is placed with is revived.  
This would also have an added benefit of indexing the note on the unit_number of the entity resulting in faster lookups

**Comment by NiftyManiac** [comment]
Not a fan of that idea... I don't like ghosts having invisible state that only shows up when they're built. Though I can't think of a better fix besides searching all nearby entities on every on_construction. Maybe I can use on_put_item to figure out what ghosts will be deleted by the placement.

**Comment by NiftyManiac** [comment]
Damn, ghosts disappearing via deconstruction planner seems completely undetectable.

**Comment by NiftyManiac** [comment]
Mostly fixed. Only time a note fails to be removed is if a ghost is deconstructed without the invis_note. Probably nothing I can do there, since no events are fired.
