### ISSUE TITLE
Error on_marked_for_deconstruction player index is optional

### ISSUE THREAD

**Issue by Nexela** [NiftyManiac/factorio-stickynotes#9]
https://forums.factorio.com/posting.php?mode=reply&f=92&t=30980#pr242272

untested fix change line #663 to

```lua
local force = (event.player_index and game.players[event.player_index].force) or (ent.last_user and ent.last_user.force) or ent.force
```
This will Use the player_index force if present otherwise the ent.force. Not sure how this will work for trees /neutral as it is untested.

**Comment by NiftyManiac** [comment]
Didn't see this but fixed it in a recent release. Dunno what happens with trees, should check that at some point.

**Comment by Nexela** [comment]
Your fix misses the last_user check, Including this check will will have much better chance of returning the correct player index

**Comment by NiftyManiac** [comment]
Oh right, good call.
